select * from anthem.w9_legal_entity
where tin='465227149';

select * from anthem.w9_organization
where w9_legal_entity_id=507076;

select * from anthem.organization
where id=61;

select * from anthem_jn.w9_organization;
--where w9_legal_entity_id=507076;

select * from anthem_jn.organization;

SELECT
	    WO.JOURNAL_ID,
	    WO.W9_LEGAL_ENTITY_ID,
        O.DESCRIPTION AS ORGANIZATION_NAME,
		DATAOWNER.DISPLAY_NAME AS DATA_OWNER_NAME,
		WO.CHANGE,
		WO.CHANGED_AT,
		WO.SESSION_USER,
		WO.PROXY_USER,
		WO.OS_USER,
		WO.OS_HOST,
		WO.APP_ID,
		WO.TRANSACTION_ID
	FROM ANTHEM_JN.W9_ORGANIZATION WO
    JOIN ANTHEM_JN.ORGANIZATION O ON O.ID = WO.ORGANIZATION_ID
	JOIN CORE_JN.DATA_OWNER DATAOWNER ON DATAOWNER.ID = O.DATA_OWNER_ID
    WHERE wo.w9_legal_entity_id = 506479
    order by wo.changed_at;
    
SELECT
(
SELECT tmp.DESCRIPTION
FROM (SELECT DENSE_RANK() OVER (PARTITION BY o.id ORDER BY CHANGED_AT DESC) S_RANK, o.*
FROM anthem_jn.ORGANIZATION o
WHERE o.ID = wo.ORGANIZATION_ID AND o.CHANGED_AT < wo.changed_at) tmp
WHERE S_RANK = 1
) ORGANIZATION_NAME
,wo.CHANGED_AT , wo.*
FROM
anthem_jn.W9_ORGANIZATION wo
WHERE wo.W9_LEGAL_ENTITY_ID = 506479
ORDER BY wo.CHANGED_AT;

SELECT
o_n.description
,wo.CHANGED_AT , wo.*
FROM
anthem_jn.W9_ORGANIZATION wo
LEFT OUTER JOIN
(SELECT * FROM
(SELECT DENSE_RANK() OVER (PARTITION BY o.id ORDER BY CHANGED_AT DESC) S_RANK, o.*
FROM anthem_jn.ORGANIZATION o
) WHERE S_RANK = 1) o_n ON o_n.ID = wo.ORGANIZATION_ID
WHERE wo.W9_LEGAL_ENTITY_ID = 506479
ORDER BY wo.CHANGED_AT;

-- Wed 4/27 
    SELECT
	    WO.JOURNAL_ID,
	    WO.W9_LEGAL_ENTITY_ID,
        O_N.DESCRIPTION AS ORGANIZATION_NAME,
		DATAOWNER.DISPLAY_NAME AS DATA_OWNER_NAME,
		WO.CHANGE,
		WO.CHANGED_AT,
		WO.SESSION_USER,
		WO.PROXY_USER,
		WO.OS_USER,
		WO.OS_HOST,
		WO.APP_ID,
		WO.TRANSACTION_ID
	FROM ANTHEM_JN.W9_ORGANIZATION WO
    LEFT OUTER JOIN (SELECT * FROM
         (SELECT DENSE_RANK() OVER
                 (PARTITION BY O.ID ORDER BY CHANGED_AT DESC) S_RANK, O.ID, O.DESCRIPTION, O.DATA_OWNER_ID FROM ANTHEM_JN.ORGANIZATION O)
          WHERE S_RANK = 1) O_N
          ON O_N.ID = WO.ORGANIZATION_ID
	JOIN CORE_JN.DATA_OWNER DATAOWNER ON DATAOWNER.ID = O_N.DATA_OWNER_ID;
