SELECT * FROM (SELECT
DENSE_RANK() OVER (ORDER BY cd.ADDRESS1, cd.CITY, cd.STATE, c.ID) S_RANK,
c.ID CLINIC_ID,
c.COMMON_NAME,
c.SHARED_PROPERTY,
c.EFFECTIVE_FROM,
c.EFFECTIVE_TO,
ANTHEM.CLINIC_DHMO(c.ID) dhmo_processing_required,
ANTHEM.CLINIC_HAS_PDO_HMO(C.ID) HAS_PDO_HMO,
CASE WHEN dc.CLINIC_ID IS NULL THEN 'N' ELSE 'Y' END diversified,
w9.IRS_NAME,
w9.TIN,
w9.DELEGATED_CREDENTIALING,
lg.GROUP_NAME,
cd.ID dir_ID,
cd.ADDRESS1 dir_ADDRESS1,
cd.ADDRESS2 dir_ADDRESS2,
cd.ADDRESS3 dir_ADDRESS3,
cd.CITY dir_CITY,
cd.STATE dir_STATE,
cd.ZIP_CODE dir_ZIP_CODE,
cd.COUNTY dir_COUNTY,
cd.COUNTRY dir_COUNTRY,
cd.PROVINCE dir_PROVINCE,
cd.LATITUDE dir_LATITUDE,
cd.LONGITUDE dir_LONGITUDE,
cpcp.ID cpcp_ID,
cpcp.PHONE_NO cpcp_PHONE_NO,
cpcp.AREA_CODE cpcp_AREA_CODE,
cpcp.COUNTRY_CODE cpcp_COUNTRY_CODE,
cpcp.CITY_CODE cpcp_CITY_CODE,
cpcp.ACCESS_CODE cpcp_ACCESS_CODE,
cpcp.EXTENSION cpcp_EXTENSION,
cpcp.DISPLAY cpcp_DISPLAY,
cpcf.ID cpcf_ID,
cpcf.PHONE_NO cpcf_PHONE_NO,
cpcf.AREA_CODE cpcf_AREA_CODE,
cpcf.COUNTRY_CODE cpcf_COUNTRY_CODE,
cpcf.CITY_CODE cpcf_CITY_CODE,
cpcf.ACCESS_CODE cpcf_ACCESS_CODE,
cpcf.EXTENSION cpcf_EXTENSION,
cpcf.DISPLAY cpcf_DISPLAY,
npiClin.ID clinic_npi_id,
npiClin.NPI clinic_npi,
npiCorp.ID corp_npi_id,
npiCorp.NPI corp_npi
FROM CLINIC c 
LEFT OUTER JOIN CLINIC_ALIAS ca ON c.ID = ca.MASTER_ID
LEFT OUTER JOIN CLINIC_ADDRESS cd ON c.ID = cd.CLINIC_ID AND cd.TYPE = 'D'
LEFT OUTER JOIN (SELECT npi.ID, npi.NPI, nc.CLINIC_ID FROM NPI_CORPORATE nc JOIN NPI npi ON nc.NPI_ID = npi.ID) npiCorp ON c.ID = npiCorp.CLINIC_ID 
LEFT OUTER JOIN (SELECT npi.ID, npi.NPI, nc.CLINIC_ID FROM NPI_CLINIC nc JOIN NPI npi ON nc.NPI_ID = npi.ID) npiClin ON c.ID = npiClin.CLINIC_ID
LEFT OUTER JOIN DIVERSIFIED_CLINIC dc ON c.ID = dc.CLINIC_ID AND dc.BOUND = 'Y' AND SYSDATE BETWEEN dc.EFFECTIVE_FROM AND NVL(dc.EFFECTIVE_TO, SYSDATE)
LEFT OUTER JOIN CLINIC_PHONE_CONTACT cpcp ON c.ID = cpcp.CLINIC_ID AND cpcp."TYPE" = 'P'
LEFT OUTER JOIN CLINIC_PHONE_CONTACT cpcf ON c.ID = cpcf.CLINIC_ID AND cpcf."TYPE" = 'F'
LEFT OUTER JOIN (SELECT CLINIC_ID, MAX(NVL(EFFECTIVE_TO, SYSDATE)) CW_TO_DATE FROM CLINIC_W9 cw GROUP BY CLINIC_ID) cw_date ON c.ID = cw_date.CLINIC_ID 
LEFT OUTER JOIN CLINIC_W9 cw ON c.ID = cw.CLINIC_ID AND cw_date.CW_TO_DATE = NVL(cw.EFFECTIVE_TO, SYSDATE) 
LEFT OUTER JOIN W9_LEGAL_ENTITY w9 ON cw.W9_ID = w9.ID 
LEFT OUTER JOIN LARGE_GROUP_TINS lgt ON w9.TIN = lgt.TIN 
LEFT OUTER JOIN LARGE_GROUP lg ON lgt.LARGE_GROUP_ID = lg.ID 
 
 WHERE NVL(ca.DUPLICATE_ID, c.ID) = :clinicId) WHERE S_RANK BETWEEN (:pageIndex * :pageSize + 1) AND ((:pageIndex + 1) * :pageSize)