COLUMN col1 NEW_VALUE vdate NOPRINT
    select to_char(sysdate,'YYYYMMDDHH24MISS') col1 from dual;
COLUMN col2 NEW_VALUE vdb NOPRINT
    select name col2 from v$database;
COLUMN col3 NEW_VALUE vuser NOPRINT
    select user col3 from dual;

SET SERVEROUTPUT ON SIZE 1000000
SET LINESIZE     600
SET PAGESIZE     200
SET TRIMSPOOL    ON
SET ECHO         ON
SET TIMING       ON
SET HEADING      ON

SPOOL sr1562_&vdb._&vuser._&vdate..log

--SR1562
-- New CRM Role 'HORIZ CSR'
INSERT INTO SOT01.FND_VALID_CODE_CHILD (VALID_CODE_CHILD_ID,VALID_CODE_PARENT_ID,STATUS_IND,ATTRIBUTE_1_CHAR,ATTRIBUTE_2_CHAR,INS_PRGM,INS_USER,INS_DATE) VALUES (XXXXX, 8,'A','HORIZ CSR'             ,'A','SR1562',USER,SYSDATE);

-- Permissions: Membership, Claims, Provider, Group Benefits
DECLARE
 VPORT NUMBER (10,0);
BEGIN
 SELECT MIN(SERVER_PORT) INTO VPORT FROM SOT01.FND_FUNCTIONAL_MATRIX;
 INSERT INTO SOT01.FND_FUNCTIONAL_MATRIX (FUNCTIONAL_MATRIX_ID,ROLE_VC,APPLICATION_VC,FUNCTION_VC,SUB_FUNCTION_VC,ACTION_VC,INS_PRGM,INS_USER,INS_DATE,APPLICATION_CONTEXT,SERVER_PORT,LANDING_PAGE,APPLICATION_ORDER,FUNCTION_ORDER,SUB_FUNCTION_ORDER,STATUS_CHECK_FILE,ACTION_MAPPING) VALUES (FUNCTIONAL_MATRIX_ID_SEQ.NEXTVAL,XXXXX,3005,3007,'','','SR1562', USER, SYSDATE,'/fs',vport,'/generateNavigation.do?appName=CRM',1,1,null,'/status/check.html','');
 INSERT INTO SOT01.FND_FUNCTIONAL_MATRIX (FUNCTIONAL_MATRIX_ID,ROLE_VC,APPLICATION_VC,FUNCTION_VC,SUB_FUNCTION_VC,ACTION_VC,INS_PRGM,INS_USER,INS_DATE,APPLICATION_CONTEXT,SERVER_PORT,LANDING_PAGE,APPLICATION_ORDER,FUNCTION_ORDER,SUB_FUNCTION_ORDER,STATUS_CHECK_FILE,ACTION_MAPPING) VALUES (FUNCTIONAL_MATRIX_ID_SEQ.NEXTVAL,XXXXX,3005,3008,'','','SR1562', USER, SYSDATE,'/fs',vport,'/generateNavigation.do?appName=CRM',1,2,null,'/status/check.html','');
 INSERT INTO SOT01.FND_FUNCTIONAL_MATRIX (FUNCTIONAL_MATRIX_ID,ROLE_VC,APPLICATION_VC,FUNCTION_VC,SUB_FUNCTION_VC,ACTION_VC,INS_PRGM,INS_USER,INS_DATE,APPLICATION_CONTEXT,SERVER_PORT,LANDING_PAGE,APPLICATION_ORDER,FUNCTION_ORDER,SUB_FUNCTION_ORDER,STATUS_CHECK_FILE,ACTION_MAPPING) VALUES (FUNCTIONAL_MATRIX_ID_SEQ.NEXTVAL,XXXXX,3005,3009,'','','SR1562', USER, SYSDATE,'/fs',vport,'/generateNavigation.do?appName=CRM',1,3,null,'/status/check.html','');
 INSERT INTO SOT01.FND_FUNCTIONAL_MATRIX (FUNCTIONAL_MATRIX_ID,ROLE_VC,APPLICATION_VC,FUNCTION_VC,SUB_FUNCTION_VC,ACTION_VC,INS_PRGM,INS_USER,INS_DATE,APPLICATION_CONTEXT,SERVER_PORT,LANDING_PAGE,APPLICATION_ORDER,FUNCTION_ORDER,SUB_FUNCTION_ORDER,STATUS_CHECK_FILE,ACTION_MAPPING) VALUES (FUNCTIONAL_MATRIX_ID_SEQ.NEXTVAL,XXXXX,3005,3011,'','','SR1562', USER, SYSDATE,'/fs',vport,'/generateNavigation.do?appName=CRM',1,4,null,'/status/check.html','');
END;
/
-- end of SR1562													
											
SPOOL OFF
EXIT

